const
  OGRERR_NONE* = 0.cint
  OGRERR_NOT_ENOUGH_DATA* = 1.cint
  OGRERR_NOT_ENOUGH_MEMORY* = 2.cint
  OGRERR_UNSUPPORTED_GEOMETRY_TYPE* = 3.cint
  OGRERR_UNSUPPORTED_OPERATION* = 4.cint
  OGRERR_CORRUPT_DATA* = 5.cint
  OGRERR_FAILURE* = 6.cint
  OGRERR_UNSUPPORTED_SRS* = 7.cint
  OGRERR_INVALID_HANDLE* = 8.cint
  OGRERR_NON_EXISTING_FEATURE* = 9.cint


